### ISSUE TITLE
can we make it easier for people to see what is installed here?

### ISSUE THREAD

**Issue by msalganik** [open-review-toolkit/vagrant-build#1]
@lukebaker 

I think that a simple README for vagrant-build would help so that people can know what is the VM.  

Is this the list of things that are installed?  A link to his might be enough.  https://github.com/open-review-toolkit/vagrant-build/blob/master/provisioning/setup.yml

**Comment by lukebaker** [comment]
@msalganik I've added a README in 0c5983a98. Does that cover what you had in mind?

**Comment by msalganik** [comment]
Yes, perfect.  I'm closing this issue.  Thanks.
